# Generated by Django 3.2.15 on 2022-08-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crsid', models.CharField(max_length=8)),
                ('full_name', models.CharField(max_length=30)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('chat', models.TextField()),
                ('event_type', models.CharField(choices=[('May Ball', 'May Ball'), ('Queer Get Down', 'Queer Get Down'), ('Wednesday Revs', 'Wednesday Revs'), ('Sunday Lolas', 'Sunday Lolas'), ("Captain's Cocktails", "Captain's Cocktails"), ('Friday Mash', 'Friday Mash'), ('Saturday Mash', 'Saturday Mash'), ('Other', 'Other')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialties',
            name='doctors',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Specialties',
        ),
    ]
